'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Items', [
      {
        name: 'SLA 3D printer PR-015',
        partnumber: 'FA-1834',
        description: 'Desktop SLA 3D printer PR-015, print size 200x250x175mm',
        status: true,
        workcenter1: 'CNC',
        descrroute1: '1.Cut aluminum profiles to the size 2. Machine metal brackets',
        cycletime1: 3.76,
        workcenter2: 'SMT',
        descrroute2: '1. Assemble controls board',
        cycletime2: 1.2,
        workcenter3: 'TST',
        descrroute3: '1. Test controls board',
        cycletime3: 2.3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'PLA 3D printer',
        partnumber: 'FA-1766',
        description: 'Desktop PLA 3D printer PR-016, print size 250x350x275mm',
        status: true,
        workcenter1: 'CNC',
        descrroute1: '1.Cut aluminum profiles to the size 2. Machine metal brackets',
        cycletime1: 2.5,
        workcenter2: 'SMT',
        descrroute2: '1. Assemble controls board',
        cycletime2: 1.8,
        workcenter3: 'TST',
        descrroute3: '1. Test controls board',
        cycletime3: 2.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'SLS 3D printer',
        partnumber: 'FA-3190',
        description: 'Desktop SLS 3D printer PR-017, print size 220x2750x160mm',
        status: true,
        workcenter1: 'AC1',
        descrroute1: '1. Assemble of  X-Y Table for FA-3190',
        cycletime1: 12.6,
        workcenter2: 'AC2',
        descrroute2: '1. Assemble of X-Axis  for FA-3190 2. Assemble of Y-Axis  for FA-3190 3. Assemble of Z-Axis  for FA-3190',
        cycletime2: 11.7,
        workcenter3: 'FAS',
        descrroute3: '1. Assemble SLA 3D printer FA-3190 2. Test Final assembly 3. Pack the device',
        cycletime3: 13.6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Original Prusa SL1',
        partnumber: 'OP-SL168',
        description: 'Professional LCD 3D printer OP-SL168, print size 400x237x225mm',
        status: true,
        workcenter1: 'CNC',
        descrroute1: '1.Cut aluminum profiles to the size 2. Machine metal brackets',
        cycletime1: 3.76,
        workcenter2: 'SMT',
        descrroute2: '1. Assemble controls board',
        cycletime2: 1.2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Liquid Crystal Precision 1.5',
        partnumber: 'LCP-1.32L',
        description: 'Professional Desktop LCD 3D printer, print size 121x68x160mm',
        status: true,
        workcenter1: 'SMT',
        descrroute1: '1. Assemble controls board',
        cycletime1: 1.8,
        workcenter2: 'TST',
        descrroute2: '1. Test controls board',
        cycletime2: 2.5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'DWS XFAB 3D printer',
        partnumber: 'XFAB5.83L',
        description: 'Professional Desktop SLA 3D printer, print size 180x180x180mm',
        status: true,
        workcenter1: 'CNC',
        descrroute1: '1.Cut aluminum profiles to the size 2. Machine metal brackets',
        cycletime1: 3.76,
        workcenter2: 'AC1',
        descrroute2: '1. Assemble of  X-Y Table for XFAB5.83L',
        cycletime2: 12.6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'B9Creations B9 Core 550',
        partnumber: 'B9C658368L',
        description: 'Professional Desktop DLP 3D printer, print size 597x419x267mm',
        status: true,
        workcenter1: 'FAS',
        descrroute1: '1. Assemble SLA 3D printer B9C658368L 2. Test Final assembly 3. Pack the device',
        cycletime1: 13.6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'EnvisionTEC Micro Plus HD',
        partnumber: 'EM-MPHD013L',
        description: 'Professional LCD 3D printer EM-MPHD013L, print size 228x241x635mm',
        status: false,
        workcenter1: 'CNC',
        descrroute1: '1.Cut aluminum profiles to the size 2. Machine metal brackets',
        cycletime1: 3.76,
        workcenter2: 'FAS',
        descrroute2: '1. Assemble SLA 3D printer EM-MPHD013L 2. Test Final assembly 3. Pack the device',
        cycletime2: 13.6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
