'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Orders', [
      {
        itemname: 'SLA 3D printer PR-015',
        itempartnum: 'FA-1834',
        itemsid: 1,
        number: 'ORN-1',
        quantity: 10,
        promiseddate: '2021-08-30 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'PLA 3D printer',
        itempartnum: 'FA-1766',
        itemsid: 2,
        number: 'ORN-2',
        quantity: 11,
        promiseddate: '2021-08-21 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'SLS 3D printer',
        itempartnum: 'FA-3190',
        itemsid: 3,
        number: 'ORN-3',
        quantity: 10,
        promiseddate: '2021-08-31 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'Original Prusa SL1',
        itempartnum: 'OP-SL168',
        itemsid: 4,
        number: 'ORN-4',
        quantity: 7,
        promiseddate: '2021-08-22 00:00:00+03',
        priority: 2,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'Original Prusa SL1',
        itempartnum: 'OP-SL168',
        itemsid: 4,
        number: 'ORN-5',
        quantity: 4,
        promiseddate: '2021-08-25 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'Liquid Crystal Precision 1.5',
        itempartnum: 'LCP-1.32L',
        itemsid: 5,
        number: 'ORN-6',
        quantity: 2,
        promiseddate: '2021-08-25 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'B9Creations B9 Core 550',
        itempartnum: 'B9C658368L',
        itemsid: 7,
        number: 'ORN-7',
        quantity: 1,
        promiseddate: '2021-08-27 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'SLS 3D printer',
        itempartnum: 'B9C658368L',
        itemsid: 3,
        number: 'ORN-8',
        quantity: 1,
        promiseddate: '2021-08-26 00:00:00+03',
        priority: 1,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'B9Creations B9 Core 550',
        itempartnum: 'B9C658368L',
        itemsid: 7,
        number: 'ORN-9',
        quantity: 3,
        promiseddate: '2021-08-27 00:00:00+03',
        priority: 3,
        status: 'Closed',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'DWS XFAB 3D printer',
        itempartnum: 'XFAB5.83L',
        itemsid: 6,
        number: 'ORN-10',
        quantity: 4,
        promiseddate: '2021-08-29 00:00:00+03',
        priority: 1,
        status: 'Open',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'PLA 3D printer',
        itempartnum: 'FA-1766',
        itemsid: 2,
        number: 'ORN-11',
        quantity: 6,
        promiseddate: '2021-09-02 00:00:00+03',
        priority: 2,
        status: 'Created',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'DWS XFAB 3D printer',
        itempartnum: 'XFAB5.83L',
        itemsid: 6,
        number: 'ORN-12',
        quantity: 2,
        promiseddate: '2021-08-31 00:00:00+03',
        priority: 3,
        status: 'Created',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'Liquid Crystal Precision 1.5',
        itempartnum: 'LCP-1.32L',
        itemsid: 5,
        number: 'ORN-13',
        quantity: 1,
        promiseddate: '2021-09-03 00:00:00+03',
        priority: 1,
        status: 'Created',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'PLA 3D printer',
        itempartnum: 'FA-1766',
        itemsid: 2,
        number: 'ORN-14',
        quantity: 5,
        promiseddate: '2021-09-07 00:00:00+03',
        priority: 1,
        status: 'Created',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        itemname: 'SLA 3D printer PR-015',
        itempartnum: 'FA-1834',
        itemsid: 1,
        number: 'ORN-15',
        quantity: 5,
        promiseddate: '2021-09-04 00:00:00+03',
        priority: 1,
        status: 'Created',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Orders', null, {});
  },
};
