export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
//
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FALI';
//
export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAIL = 'CREATE_ITEM_FAIL';
//
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';
//
export const LOGOUT_USER = 'LOGOUT_USER';
//
export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAIL = 'EDIT_USER_FAIL';
//
export const GET_LIST_OF_ITEMS = 'GET_LIST_OF_ITEMS';
export const GET_LIST_OF_ITEMS_SUCCESS = 'GET_LIST_OF_ITEMS_SUCCESS';
export const GET_LIST_OF_ITEMS_FAIL = 'GET_LIST_OF_ITEMS_FAIL';
//
export const EDIT_ORDER = 'EDIT_ORDER';
export const EDIT_ORDER_SUCCESS = 'EDIT_ORDER_SUCCESS';
export const EDIT_ORDER_FAIL = 'EDIT_ORDER_SUCCESS';
//
export const CREATE_WORK_CENTER = 'CREATE_WORK_CENTER';
export const CREATE_WORK_CENTER_SUCCESS = 'CREATE_WORK_CENTER_SUCCESS';
export const CREATE_WORK_CENTER_FAIL = 'CREATE_WORK_CENTER_FAIL';
//
export const EDIT_WORK_CENTER = 'EDIT_WORK_CENTER';
export const EDIT_WORK_CENTER_SUCCESS = 'EDIT_WORK_CENTER_SUCCESS';
export const EDIT_WORK_CENTER_FAIL = 'EDIT_WORK_CENTER_FAIL';
//
export const EDIT_ITEM = 'EDIT_ITEM';
export const EDIT_ITEM_SUCCES = 'EDIT_ITEM_SUCCES';
export const EDIT_ITEM_FAIL = 'EDIT_ITEM_FAIL';
//
export const GET_WORK_CENTERS = 'GET_WORK_CENTERS';
export const GET_LIST_OF_USERS = 'GET_LIST_OF_USERS';
export const GET_LIST_OF_ORDERS = 'GET_LIST_OF_ORDERS';
export const GET_ORDER_IN_WORK = 'GET_ORDER_IN_WORK';
export const GET_RANDOM_ORDER_NUM = 'GET_RANDOM_ORDER_NUM';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const TAKE_ORDER_IN_WORK = 'TAKE_ORDER_IN_WORK';

export const SUBMIT_ITEM_PARTS = 'SUBMIT_ITEM_PARTS';
export const CLOSE_ORDER = 'CLOSE_ORDER';
